apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-027111-oam-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/shlapolosa/service-027111-gitops.git
    targetRevision: HEAD
    path: oam/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
